package net.jidget.app;

import javafx.application.Platform;
import javax.swing.AbstractListModel;
import javax.swing.UIManager;

/**
 *
 * @author Arian Treffer
 */
public class JidgetSelection extends javax.swing.JFrame {

    private final JidgetManager jManager;
    private final JidgetListModel listModel = new JidgetListModel();
    private String[] jidgetIDs;
    private String currentJidget;
    
    /**
     * Creates new form JidgetSelection
     */
    public JidgetSelection(JidgetManager jManager) {
        this.jManager = jManager;
        jidgetIDs = jManager.getAllJidgetIDs();
        initComponents();
        lstJidgets.setModel(listModel);
        if (jidgetIDs.length > 0) {
            lstJidgets.setSelectedIndex(0);
        }
    }

    private void showJidget(String currentJidget) {
        this.currentJidget = currentJidget;
        lblJidgetID.setText(currentJidget);
        cbJidgetActive.setSelected(jManager.isActive(currentJidget));
    }
    
    private class JidgetListModel extends AbstractListModel<String> {

        @Override
        public int getSize() {
            return jidgetIDs.length;
        }

        @Override
        public String getElementAt(int index) {
            return jidgetIDs[index];
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        lstJidgets = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        lblJidgetID = new javax.swing.JLabel();
        cbJidgetActive = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();

        lstJidgets.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstJidgets.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstJidgetsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstJidgets);

        lblJidgetID.setText("jLabel1");

        cbJidgetActive.setText("active");
        cbJidgetActive.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbJidgetActiveItemStateChanged(evt);
            }
        });
        cbJidgetActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJidgetActiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJidgetID)
                    .addComponent(cbJidgetActive))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJidgetID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbJidgetActive)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 186, Short.MAX_VALUE)
                .addComponent(btnExit))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        jManager.exit();
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void lstJidgetsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstJidgetsValueChanged
        if (!evt.getValueIsAdjusting()) {
            int i = lstJidgets.getSelectedIndex();
            showJidget(jidgetIDs[i]);
        }
    }//GEN-LAST:event_lstJidgetsValueChanged

    private void cbJidgetActiveItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbJidgetActiveItemStateChanged
        if (cbJidgetActive.isSelected()) {
            boolean success = jManager.show(currentJidget);
            cbJidgetActive.setSelected(success);
        } else {
            jManager.hide(currentJidget);
        }
        
    }//GEN-LAST:event_cbJidgetActiveItemStateChanged

    private void cbJidgetActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJidgetActiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJidgetActiveActionPerformed

    private static JidgetSelection selectionDlg = null;
    
    /**
     * @param args the command line arguments
     */
    public static void Show(final JidgetManager jManager) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
            UIManager.setLookAndFeel(
                UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JidgetSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                if (selectionDlg == null) selectionDlg = new JidgetSelection(jManager);
                selectionDlg.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JCheckBox cbJidgetActive;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblJidgetID;
    private javax.swing.JList lstJidgets;
    // End of variables declaration//GEN-END:variables
}
